### PR TITLE
Use latest devise

### PR DESCRIPTION
**Pull request by pjambet**
This will allow upgrades to rails 5 and ruby 2.5.0

### CODE REVIEW

**Comment by zedtux** [comment]
@pjambet are the tests passing on your branch?

**Comment by pjambet** [comment]
@zedtux Yes, I've been running this in production for a few weeks without any issues.

**Comment by zedtux** [comment]
I'm talking about the automated tests (minitest)

**Comment by pjambet** [comment]
Sorry, replied too quickly, my bad.

Tests don't even pass locally on upstream master, so I can't tell.

**Comment by zedtux** [comment]
Okay, so same on my side, thank you @pjambet for your answer 👍

**Review by julienbourdeau — APPROVED** [review]

**Comment by pjambet** [comment]
This thing has been opened for a while, and I don't need it anymore, so closing this.

**Pull request closed without merging**
